In [1]:
#numpy is a python library used for working with arrays. 
#The array object in numpy is called ndarray and arrays are stored at one continous place in memory 
#unlike the lists thus processes can access and manipulate them very easily.
#we can perform mathematical and logical operations
import numpy as np


In [43]:
arr = np.array([1,2,3,4,5])#to create an ndarray we can give the list/tuple or any array object into the array() method ,
#which thereby converts the list/tuple/array to an ndarray.
print(arr)
print(type(arr))#gives the type of numpy arrays which is ndarray
#creating arrays of various dimensions
a = np.array(24)
b= np.array([23,31])
c= np.array([[34,65,47],[34,78,90]])
print(c[1,2])#prints the 3rd element on the 2nd row
print(a.ndim)
print(b.ndim)
print(c.ndim)
#creating array of any no.of dimensions using ndmin attribute
arr = np.array([4,7,6,5,3,4],ndmin = 6)
print(arr.base)#interpretes whether its a copy or a view if none is returned its considered a view,
#incase it returns the same array its considered a copy
print('dimensions of array',arr.shape)#finding the shape of the array using shape attribute
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])#return every other element from index 1 to index 5
arr = np.array([1, 2, 3, 4], dtype='S')#an array of datatype String is created 
print(arr)
print(arr.dtype)
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
#The example below returns three 2-D arrays, but they are split along the row using hsplit() function
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
arr = np.hsplit(arr, 3)
print(arr)


[1 2 3 4 5]
<class 'numpy.ndarray'>
90
0
1
2
[4 7 6 5 3 4]
dimensions of array (1, 1, 1, 1, 1, 6)
[2 4]
[b'1' b'2' b'3' b'4']
|S1
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [21]:
#iterating arrays
import numpy as np
arr = np.array([1, 742, 733, 237,654, 8, 63, 21])
#sort the array
arr = np.sort(arr)
print('sorted array',arr)

# Create an empty list
emptyarr = []
# go through each element in arr
for element in arr:
  # if the element is odd, set the value to True, otherwise False:
  if element%2==1:
    emptyarr.append(True)
  else:
    emptyarr.append(False)

oddarr = arr[emptyarr]

print(emptyarr)
print(oddarr)
#serching in even number in ndarrays using where method
evenarr = np.where(arr%2 == 0)
print(evenarr)#returns the indices in which even numbers are present




sorted array [  1   8  21  63 237 654 733 742]
[True, False, True, True, True, False, True, False]
[  1  21  63 237 733]
(array([1, 5, 7], dtype=int64),)


In [36]:
#generating random numbers using random module of numpy
from numpy import random
import numpy as np

In [39]:
a = random.randint(25)#generates an integer randomly from 0 to 25
print(a)
x=random.randint(60,size=(3))# generates a random array containing 3 random integers from 0 to 60
print(x)
b= random.rand(10) #generates a random float from 0 to 10
print(b)
arr = random.choice([8, 5, 2, 10], size=(3, 5))#generates a 2d array of 3 rows containing 5 elements each from the given choice of array
x = random.choice([3,7,8,9,3],p = [0.1,0.2,0.5,0.1,0.1],size=(3,5))#generates a 2d array with the given choice according to the probability
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)#the shuffle() method makes changes to the original array,it changes the arrangement of the elements.
print(arr)
print(random.permutation(arr))#The permutation() method returns a re-arranged array and leaves the original array un-changed


23
[20  6 55]
[0.83568932 0.22800624 0.6608494  0.28885026 0.32068462 0.99053804
 0.07585125 0.58421789 0.23113761 0.69623157]
[3 4 2 1 5]
[1 3 2 5 4]
